{% set name = "docrepr" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3ad62ecdaa0b7ab90dcd9c29abc98cae7d61d09339f18396d4ca5b8ab41c8b90

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python  >=3.6
    - pip
  run:
    - python  >=3.6
    - docutils
    - jinja2
    - sphinx <4

test:
  imports:
    - docrepr
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/spyder-ide/docrepr
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Generate rich representations for docstrings
  dev_url: https://github.com/spyder-ide/docrepr

extra:
  recipe-maintainers:
    - CAM-Gerlach
    - SylvainCorlay
    - martinRenou
